"use client"
import { getRequest } from "@/api_service"
import Navbar from "@/componenets/Navbar"
import { assignUser } from "@/redux/features/auth-slice"
import { notFound } from "next/navigation"
import { useEffect, useState } from "react"
import { useDispatch, useSelector } from "react-redux"

export const metadata = {
    title: 'Gogo | Customer',
    description: 'Generated by create next app',
}

export default function CustomerLayout({ children, params }) {
    const dispatch = useDispatch()
    const {user} = useSelector(state => state.authReducer)

    useEffect(() => {
        getCustomer()
    }, [])

    const getCustomer = async () => {
        const response = await getRequest(`/api/users/${params.id}`)
        dispatch(assignUser(response))
    }

    if (user) {
        return (
            <section>
                <Navbar />
                <section>
                    {children}
                </section>
            </section>       
        )
    }
}